### ISSUE TITLE
Error when installing using yarn

### ISSUE THREAD

**Issue by threadhack** [wowmaking/react-native-iron-source#14]
When I trying to install using Yarn I'm getting the error:
`yarn add @wowmaking/react-native-iron-source`
`error An unexpected error occurred: "expected hoisted manifest for \"@wowmaking/react-native-iron-source#react-native#@react-native-community/cli#metro\"".
`
Any suggestions about how it could be fixed?

**Comment by fearmear** [comment]
Please specify your React Native and yarn versions.

**Comment by threadhack** [comment]
Yarn: 1.16.0
React Native: 0.59.9
I have tried installing using NPM and it went fine.

**Comment by StanislavMayorov** [comment]
@threadhack We can't reproduce it. We've tested on mac and windows using yarn 1.16.0 and new RN 0.60.0 repo.

**Comment by StanislavMayorov** [comment]
It's reproduced exactly in 0.59.9

**Comment by StanislavMayorov** [comment]
update package to `2.8.5`
