### ISSUE TITLE
Could not find any matches for com.ironsource.sdk:mediationsdk:6.+

### ISSUE THREAD

**Issue by RomuloDevelop** [wowmaking/react-native-iron-source#24]
I was running react-native run android command and receive this error in the command line:

```
Could not find any matches for com.ironsource.sdk:mediationsdk:6.+ as no versions of com.ironsource.sdk:mediationsdk are available.
  Required by:
      project :app > project :@wowmaking_react-native-iron-source
```
Yarn: 1.15.0
React Native: 0.59.0

**Comment by StanislavMayorov** [comment]
Hi. Did you add https://github.com/wowmaking/react-native-iron-source#android-1 ?
```
repositories {
    maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
}
```

**Comment by anatolysamoilenko** [comment]
@RomuloDevelop  Add all repos and dependencies from this this guide https://developers.ironsrc.com/ironsource-mobile/android/mediation-networks-android/#step-1
to app/build.gradle
Basic:
`
repositories {
    maven {
        url 'https://dl.bintray.com/ironsource-mobile/android-sdk'
    }
    maven {
        url 'https://dl.bintray.com/ironsource-mobile/android-adapters'
    }
}
dependencies {
    implementation 'com.ironsource.sdk:mediationsdk:6.9.1@jar' 
}
`

**Comment by RomuloDevelop** [comment]
@StanislavMayorov  Your right, I did not see that step, sorry. However i encountered another issue in metro-builder:
```
bundling failed: Error: Unable to resolve module `react-native-iron-source` from `/**file path**/`: Module `react-native-iron-source` does not exist in the Haste module map
```
Then i changed this import:

```
import { IronSource, IronSourceRewardedVideo   } from 'react-native-iron-source';
``` 
to:
```
import { IronSource, IronSourceRewardedVideo  } from '@wowmaking/react-native-iron-source';
```
and then my rewarded video runs normally.

I think this is something obvious, but it aren't in the docs.

**Comment by RomuloDevelop** [comment]
**Problem was solved**

**Comment by StanislavMayorov** [comment]
@RomuloDevelop Thank you. This part of docs is outdated.
