### ISSUE TITLE
EventListeners not working for rewarded vídeos 

### ISSUE THREAD

**Issue by RomuloDevelop** [wowmaking/react-native-iron-source#26]
Hi! it's me again, i was testing rewarded video ads and noticed that eventListeners for this options are not working. In my componentDidMount i have:

``` 
IronSource.initializeIronSource(****, 'test', {
   validateIntegration: true
}).then(() => {
   console.warn('Init finished');
});
IronSourceRewardedVideo.addEventListener('ironSourceRewardedVideoDidOpen',()=>console.log('open'));
IronSourceRewardedVideo.addEventListener('ironSourceRewardedVideoAdRewarded', (reward)=>console.log(reward));
```
I invoke the test video ad in a touchable and is working as expected, the console.war in the ```initializeIronSource``` function is working well but the logs in the listeners are not showing.

By the way, i tested the interstitial ads and the listeners works well

**Comment by StanislavMayorov** [comment]
Your addEventListener looks okay. 
You could  check native logs in logcat and check mediation-setup https://github.com/wowmaking/react-native-iron-source#mediation-setup

**Comment by RomuloDevelop** [comment]
I found the error. The method ```IronSourceRewardedVideo.initializeRewardedVideo()``` need to be called at the begining for activate listeners natively.

**Comment by StanislavMayorov** [comment]
This part was removed from docs example by mistake. Thank you.
