### ISSUE TITLE
IronSource.h - file not found

### ISSUE THREAD

**Issue by trickyc0d3r** [wowmaking/react-native-iron-source#3]
Hi!
I've add framework manually, link RNIronSource library into xcode project. Make changes to framework search paths but recieve build error on IronSource.h file.
May be I need to add some other targets for library?

Node 11
RN 59.5

**Comment by StanislavMayorov** [comment]
Hi. We use iOS CocoaPods in our projects. Could you try CocoaPods installation?
@fearmear what do you think?

**Comment by getconnect2ali** [comment]
Hey,

Try remove googleMobileAds and install again, if it's there in your project.

For me it's working now.

Regards
Ali Hussain

**Comment by Coder-ACJHP** [comment]
I tried to use cocopods installation and getting same error, and as in docs mentioned we must point to bridging header in build setting but i already using bridging header for other sdk(s) thats why i can add new path for IronSource header. Please update document and include how to add path for existing header file.

How to Solve it?
Install it from cocopods
if you already have  header file in your project just add **#import <IronSource/IronSource.h>** this line in your file
else add path in build settings like explained in docs
