### ISSUE TITLE
Error: compiledebugjavawithjavac

### ISSUE THREAD

**Issue by Ricll** [wowmaking/react-native-iron-source#32]
Hi guys, 

I have tried install following all the steps, but doesn´t work.
In Getting started , you said to  add new RNIronSourcePackage() to the list returned by the getPackages() method,but I´cant found it there.
I found this method in getPackages() in MainApplication.java
![image](https://user-images.githubusercontent.com/44032539/63942570-62760780-ca44-11e9-8abe-49046488f6c9.png)

Whta I´m doing worng?
I´m using rn59.9 and I installed the https://developers.ironsrc.com/ironsource-mobile/android/android-sdk/ 

thanks

**Comment by StanislavMayorov** [comment]
Hi.
It's a typo in readme. You are right that this method is located in `MainApplication.java`. I've fixed it https://github.com/wowmaking/react-native-iron-source/pull/33.
This part of installation looks okay. Please check build errors. 
Did you add this part?
```
repositories {
    maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
}
```

**Comment by Ricll** [comment]
> Hi.
> It's a typo in readme. You are right that this method is located in `MainApplication.java`. I've fixed it #33.
> This part of installation looks okay. Please check build errors.
> Did you add this part?
> 
> ```
> repositories {
>     maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
> }
> ```

Hi, StanislavMayorov. Yes, I did. I will do everything from beginning.

**Comment by StanislavMayorov** [comment]
You can check the example app.
https://github.com/wowmaking/react-native-iron-source/tree/master/ExampleApp

**Comment by Ricll** [comment]
> You can take a look at the example app.
> https://github.com/wowmaking/react-native-iron-source/tree/master/ExampleApp

Yes, I saw it already and it´s working.
![image](https://user-images.githubusercontent.com/44032539/64020816-e4c7ff80-cb08-11e9-95e8-694831cd3e20.png)

But now, I´m stucked in the test fase. 
Do you now how can I generate an Advertising ID in react-native? 
IntegrationHelper.validateIntegration(activity);

**Comment by fearmear** [comment]
See [react-native-idfa](https://www.npmjs.com/package/react-native-idfa) package.

**Comment by StanislavMayorov** [comment]
Can I close the issue?

**Comment by Ricll** [comment]
Yes.
