### ISSUE TITLE
There's no readme in last npm release

### ISSUE THREAD

**Issue by StanislavMayorov** [wowmaking/react-native-iron-source#34]
There's no readme in last npm release.
https://www.npmjs.com/package/@wowmaking/react-native-iron-source

**Comment by fearmear** [comment]
Looks like it's a problem on NPM side [[link]](https://github.com/npm/www/issues/395)

**Comment by StanislavMayorov** [comment]
What npm and node version was used?

**Comment by fearmear** [comment]
**node -v**
v8.16.0

**npm -v**
6.4.1

**Comment by yairEO** [comment]
I also see this with my package. 

**Just now** published and I get *"Unable to find a readme"*

### https://www.npmjs.com/package/@yaireo/tagify
