### ISSUE TITLE
[Feat] IsRewardedVideoAvailable()

### ISSUE THREAD

**Issue by Insomniiak** [wowmaking/react-native-iron-source#42]
Hello, 
Would be nice to be able to get IsRewardedVideoAvailable() feature in react.

**Comment by StanislavMayorov** [comment]
Implemented in https://github.com/wowmaking/react-native-iron-source/pull/43

**Comment by StanislavMayorov** [comment]
Released https://github.com/wowmaking/react-native-iron-source/releases/tag/v3.3.0
