### ISSUE TITLE
IronSourceRewardedVideo.isRewardedVideoAvailable() is not a function on Android

### ISSUE THREAD

**Issue by tarasvakulka** [wowmaking/react-native-iron-source#47]
"@wowmaking/react-native-iron-source": "^3.2.5" 
isRewardedVideoAvailable() is not a function on Android, other methods works fine, but this not working. Guys help please, I saw that pull request merged https://github.com/wowmaking/react-native-iron-source/pull/43/commits/9f6f8db16e7ab42c4c50262b7d1f2f46b2f5e7ac#diff-0e0621f2d330e2b37f0dac091a2897ff, but this didn't work, check please

**Comment by StanislavMayorov** [comment]
This feature isn't released. Please check docs on npm. You can install unreleased version from github
