### ISSUE TITLE
How about upgrade IronSourceSDK for IOS ?

### ISSUE THREAD

**Issue by tarasvakulka** [wowmaking/react-native-iron-source#51]
I want integrate Admob mediation network, and now this require:
pod 'IronSourceSDK','6.10.0.0'
pod 'IronSourceAdMobAdapter','4.3.7.0'
But "@wowmaking/react-native-iron-source": "3.3.1" require s.dependency "IronSourceSDK", "~> 6.8" and I can not do it now, because had Pods version conflict. Also will may be some problem on IOS 13 see this article https://developers.ironsrc.com/ironsource-mobile/ios-13-ad-network-status/.
Could somebody help?
Now on 'IronSourceAdMobAdapter','4.3.4.3' I had error and admob ad not show in my app:
[ironSource SDK] ADAPTER_DELEGATE: AdMob:ISInitFailWithError 506
But integration helper said that all is ok:
--------------- AdMob --------------
2019-11-26 12:54:15.058539+0200 MovieFan[1906:563318] Adapter VERIFIED
2019-11-26 12:54:15.059189+0200 MovieFan[1906:563318] SDK - version afma-sdk-i-v7.42.2 - VERIFIED
2019-11-26 12:54:15.059322+0200 MovieFan[1906:563318] Frameworks - VERIFIED
2019-11-26 12:54:15.059476+0200 MovieFan[1906:563318] Adapter Version 4.3.3 - VERIFIED
2019-11-26 12:54:15.059528+0200 MovieFan[1906:563318]

**Comment by StanislavMayorov** [comment]
So have you got any errors on `pod install`?

**Comment by tarasvakulka** [comment]
Yes, I had pods version conflict, because @wowmaking/react-native-iron-source require "IronSourceSDK", "~> 6.8"

**Comment by fearmear** [comment]
Does changing node_modules/@wowmaking/react-native-iron-source/RNIronSource.podspec line 20 to `s.dependency "IronSourceSDK", "~> 6"` help?

**Comment by tarasvakulka** [comment]
@fearmear  yes it's help, because I create this issue with title "How about upgrade IronSourceSDK for IOS ?" I don't want edit my node_modules, yes I can fork but I hope may be owner this library in future do this upgrade, because it's great library and I want to use it

**Comment by fearmear** [comment]
I'll update the library tomorrow.

**Comment by tarasvakulka** [comment]
Thanks.

**Comment by fearmear** [comment]
Shipped in v3.3.2
