### ISSUE TITLE
Ad not showing on IOS simulator

### ISSUE THREAD

**Issue by tarasvakulka** [wowmaking/react-native-iron-source#52]
Ad show fine on real IOS device, but on IOS simulator always triggered 'ironSourceRewardedVideoUnavailable' event. Why?

**Comment by fearmear** [comment]
I think you maybe experiencing this known issue from Read Me:
> Ads may stop loading properly when "Reload" option (or CMD+R) in your React Native app was used. You have to restart the app completely if you want to check that ads load and display correctly.

**Comment by StanislavMayorov** [comment]
Ads network doesn't provide ad for your device (simulator). It's not the RN bridge issue.
You can add your devices to test device list then It would work okay for some networks. 
Please follow official testing docs https://developers.ironsrc.com/ironsource-mobile/android/integration-testing/#step-1
