### ISSUE TITLE
IronSourceRewardedVideo.isVideoRewardAvailable not working

### ISSUE THREAD

**Issue by tarasvakulka** [wowmaking/react-native-iron-source#53]
IronSourceRewardedVideo.isVideoRewardAvailable not working in @wowmaking/react-native-iron-source 3.3.2
![1575387272678](https://user-images.githubusercontent.com/20745370/70065163-4fe70d80-15f3-11ea-95d0-721e0318b1fc.jpg)
![photo_2019-12-03 17 35 48](https://user-images.githubusercontent.com/20745370/70065190-5b3a3900-15f3-11ea-8aaf-56de749cb553.jpeg)

**Comment by StanislavMayorov** [comment]
Hi. Did it work okay in 3.3.1?

**Comment by tarasvakulka** [comment]
No, it's mistake in name of method in documentation on npm and github, should be isRewardedVideoAvailable, check please

**Comment by StanislavMayorov** [comment]
I get it. Thank you. it will be uploaded to npm in the next release.
https://github.com/wowmaking/react-native-iron-source/pull/54
