### ISSUE TITLE
[QUESTION] Is it possible to pass player id to rewarded video?

### ISSUE THREAD

**Issue by 6pm** [wowmaking/react-native-iron-source#56]
I working on app where players can get free coins after they have seen video adds. I'm wondering is it possible to pass player id which will be automatically send to backend callback?

There is 'IronSource.setDynamicUserId("UserID");' method exists on Android SDK, but I don't see the relevant method in react-native sdk.

Thank you for response.

**Comment by StanislavMayorov** [comment]
Hi. It was released in 3.3.0, but it wasn't added to docs. Feel free to update it.
https://github.com/wowmaking/react-native-iron-source/pull/39

**Comment by 6pm** [comment]
That's good news! Thank you
