### ISSUE TITLE
How set custom params to callback url in Rewarded Video?

### ISSUE THREAD

**Issue by tarasvakulka** [wowmaking/react-native-iron-source#57]
Now I use userId param for this (see screenshot), but I need to set more params for each ad show. Could somebody help?
![1578570708732](https://user-images.githubusercontent.com/20745370/72065616-526e0e80-32e7-11ea-88b2-d8ddd9d0ab4f.jpg)

**Comment by StanislavMayorov** [comment]
Hi. Can you add a link to native API doc you want to use?

**Comment by tarasvakulka** [comment]
I find it IronSourceRewardedVideo.setDynamicUserId(), please add it to docs

**Comment by StanislavMayorov** [comment]
You are welcome to create a PR.
