### ISSUE TITLE
setDynamicUserId not working @wowmaking/react-native-iron-source v3.3.5

### ISSUE THREAD

**Issue by tarasvakulka** [wowmaking/react-native-iron-source#58]
setDynamicUserId not working @wowmaking/react-native-iron-source v3.3.5. Please help.
![Simulator Screen Shot - iPhone 8 - 2020-01-09 at 14 54 06](https://user-images.githubusercontent.com/20745370/72069504-f491f480-32ef-11ea-9496-3166e5f22ca9.png)

**Comment by StanislavMayorov** [comment]
Hi. Can you share a code example?

**Comment by tarasvakulka** [comment]
I called IronSource.setDynamicUserId(), because got this error, needed IronSourceRewardedVideo.setDynamicUserId()
