### ISSUE TITLE
Null is not object (evaluating 'RNTIroinSource.initialzeIron Source'

### ISSUE THREAD

**Issue by nsknight** [wowmaking/react-native-iron-source#59]
import { IronSourceBanner } from '@wowmaking/react-native-iron-source';
import { IronSource } from '@wowmaking/react-native-iron-source';

IronSource.initializeIronSource('8a19a09d', 'userId', {
  validateIntegration: true,
}).then(() => {
  console.warn('Init finished');
});

IronSourceBanner.loadBanner('LARGE');
IronSourceBanner.addEventListener('ironSourceBannerDidLoad', () => {
  console.warn('Iron Source banner loaded');
  IronSourceBanner.showBanner();
});

**Comment by StanislavMayorov** [comment]
Hi. Can you share code example?

**Comment by floelm** [comment]
I am having the same issue.

**Comment by StanislavMayorov** [comment]
Please provide enough information in bug description. RN version, react-native-iron-source and native sdk versions. What method caught the error? `initializeIronSource`? What platform is used?

**Comment by nsknight** [comment]
Error: RNIronSource.js Null is not object in UiManager 
method used both manual instigation and also link method  
bareflow expo 36.0.0
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~36.0.0",
    "@expo/vector-icons": "~10.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "~4.0.10",
    "react-navigation-stack": "~1.10.3",
    "react-navigation-tabs": "~2.6.2",
    "expo-linear-gradient": "~8.0.0",
    "expo-ads-facebook": "8.0.0",
    "react-native-paper": "3.3.0",
    "react-native-elements": "1.2.7",
    "react-native-webview": "~7.4.3"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0",
    "jest-expo": "~36.0.0"
  },
  "private": true
}

**Comment by StanislavMayorov** [comment]
We don't test expo support. I'm not familiar with expo. Did you install android/ios ironsrc sdk?

**Comment by nsknight** [comment]
can you sent me tutorial link ?

**Comment by StanislavMayorov** [comment]
README is the only documentation. There is setup for react native (`react-native init` app with android/ios folders)

**Comment by psaikali** [comment]
Chiming in! @nsknight does this library work with Expo?
I'm thinking about using it but if I can get Expo users feedback, that'd be great.

Cheers!

**Comment by knightkhan** [comment]
> Chiming in! @nsknight does this library work with Expo?
> I'm thinking about using it but if I can get Expo users feedback, that'd be great.
> 
> Cheers!

i am level beginner user.  i try it but its donot work for me
