### ISSUE TITLE
ı has this package working problem . (SOLVED)

### ISSUE THREAD

**Issue by darkegn** [wowmaking/react-native-iron-source#62]
hi  ı has this package working problem
Screenshot console : [https://prnt.sc/smqgbo](https://prnt.sc/smqgbo)

**Comment by Kubessandra** [comment]
Hi, can you provide some step to reproduce it?

React-native version:
Package version:

A bit more context on this please.

**Comment by darkegn** [comment]
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.41 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

**Comment by Kubessandra** [comment]
Could you show me your AndroidManifest.yml?

**Comment by darkegn** [comment]
[https://hastebin.com/kigajonasi.xml](https://hastebin.com/kigajonasi.xml)

**Comment by darkegn** [comment]
> Could you show me your AndroidManifest.yml?

[https://hastebin.com/kigajonasi.xml](https://hastebin.com/kigajonasi.xml)

**Comment by darkegn** [comment]
> > Could you show me your AndroidManifest.yml?
> 
> https://hastebin.com/kigajonasi.xml

debug : https://hastebin.com/eluvufedez.xml

**Comment by Kubessandra** [comment]
Ok you have a conflict with the allowBackup, true on the package and false in your app.

A quick fix can be to activate the allowBackup in your manifest.
But you can also override this by setting
```
tools:replace="android:allowBackup"
```
in your \<application\>

https://developer.android.com/studio/build/manifest-merge

**Comment by darkegn** [comment]
> Ok you have a conflict with the allowBackup, true on the package and false in your app.
> 
> A quick fix can be to activate the allowBackup in your manifest.
> But you can also override this by setting
> 
> ```
> tools:replace="android:allowBackup"
> ```
> 
> in your <application>
> 
> https://developer.android.com/studio/build/manifest-merge

problem solved thanks :)

**Comment by Kubessandra** [comment]
Could you close your Issue please?, thank you !
