### ISSUE TITLE
508 Interstitial - the server response does not contain interstitial data

### ISSUE THREAD

**Issue by darkegn** [wowmaking/react-native-iron-source#63]
hi i have error  "508 Interstitial - the server response does not contain interstitial data"

**IRON SOURCE** 
**- test device:** added
**- test ad unit active :** on

console : [https://prnt.sc/sn4cp8](https://prnt.sc/sn4cp8)
code [https://prnt.sc/sn4etd](https://prnt.sc/sn4etd)

**Comment by StanislavMayorov** [comment]
You can find this information in native SDK docs https://developers.ironsrc.com/ or support. This lib is only React Native bridge.
