### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by angelobl** [wowmaking/react-native-iron-source#68]
Im trying to launch the offerwall, followed all instructions on the README, got the "Init finished" message after running IronSource.initializeIronSource with my api key, but when I try to run IronSourceOfferwall.showOfferwall() nothing happens. Any idea what could be going wrong? Im using RN 61.5 and Android Emulator

**Comment by karapish** [comment]
Hi @angelobl. Let me know how you solved your problem. I'm facing the same issue now. Cheers!
