### ISSUE TITLE
iOS build fails with error No visible @interface for 'ISBannerSize' declares the selector 'initWithDescription:'

### ISSUE THREAD

**Issue by 0x7fs** [wowmaking/react-native-iron-source#70]
I'm trying to build this SDK (v7.0.0) for my RN app and am receiving a build error:

> No visible @interface for 'ISBannerSize' declares the selector 'initWithDescription:'

In the following location:

https://github.com/wowmaking/react-native-iron-source/blob/master/ios/RNIronSourceBanner.m#L71-L72

It appears that there may have been a change in the native iOS IronSource library that hasn't been reflected in this SDK yet. Can anyone help me with this? Thanks!

**React Native Info Output:**

System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 1.93 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/mick/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by khushbooOpenxcell** [comment]
Im facing the same issue, have you found any solution @0x7fs ?

**Comment by fearmear** [comment]
It looks like IronSourceSDK 7.0.2 isn't backwards compatible anymore.
A workaround would be downgrading it like this `pod 'IronSourceSDK', '= 7.0.0'` (add to Podfile)

**Comment by khushbooOpenxcell** [comment]
@

> It looks like IronSourceSDK 7.0.2 isn't backwards compatible anymore.
> A workaround would be downgrading it like this `pod 'IronSourceSDK', '= 7.0.0'` (add to Podfile) until I'll roll out a fix

This gives me below error on pod install:


[!] CocoaPods could not find compatible versions for pod "IronSourceSDK":
  In Podfile:
    IronSourceAdMobAdapter (= 4.3.17.1) was resolved to 4.3.17.1, which depends on
      IronSourceSDK (= 7.0.3.0)

    IronSourceSDK (= 7.0.0)

    RNIronSource (from `../node_modules/@wowmaking/react-native-iron-source`) was resolved to 7.0.0, which depends on
      IronSourceSDK (~> 7)

**Comment by khushbooOpenxcell** [comment]
@fearmear is there any way to check the compatible version of mediation SDKs for a particular IronSourceSDK version.

**Comment by fearmear** [comment]
Set adapter versions to ‘> 1’ and drop Podfile.lock. It will figure out which version of adapter is compatible with SDK automatically

**Comment by tarasvakulka** [comment]
> It looks like IronSourceSDK 7.0.2 isn't backwards compatible anymore.
> A workaround would be downgrading it like this `pod 'IronSourceSDK', '= 7.0.0'` (add to Podfile) until I'll roll out a fix

Please, roll out a fix, because we want to update IronSourceFacebookAdapter to  latest 4.3.20, that depend on IronSourceSDK', '= 7.0.3', and also receive error No visible @interface for 'ISBannerSize' declares the selector 'initWithDescription:'

Look forward to your fix, thanks)

**Comment by fearmear** [comment]
Here's a WIP fix `npm i github:wowmaking/react-native-iron-source#banner-fix`
We're still testing it. Requires Xcode 12

**Comment by tarasvakulka** [comment]
> Here's a WIP fix `npm i github:wowmaking/react-native-iron-source#banner-fix`
> We're still testing it. Requires Xcode 12
> 
> If someone would like to test it please report your experience.

Test you WIP fix, works fine, but we have bidding on and sometimes we see random crash like this:
![image](https://user-images.githubusercontent.com/20745370/97860413-c102d980-1d0a-11eb-9d8e-fda485172ecc.png)
I don't know is it related with your WIP fix, but we see such a problem. May be it's related with bidding and I should open new issue about it, please let me know.
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x7fff2043a116 (Отсутствует)
1  libobjc.A.dylib                0x7fff20177f78 objc_exception_throw
2  CoreFoundation                 0x7fff204b6cdb (Отсутствует)
3  CoreFoundation                 0x7fff204c21f8 (Отсутствует)
4  CoreFoundation                 0x7fff204a51ff (Отсутствует)
5  CoreFoundation                 0x7fff20438da3 (Отсутствует)
6  Save Pirate                    0x10f564348 -[ISAuctionDataUtils enrichToken:nonBidders:auctionHistory:sessionDepth:sessionId:bannerSize:blob:] + 229 (ISAuctionDataUtils.m:229)
7  Save Pirate                    0x10f58402e -[ISAuctionHandler generateRequest:nonBidders:auctionHistory:sessionDepth:] + 159 (ISAuctionHandler.m:159)
8  Save Pirate                    0x10f583cd0 -[ISAuctionHandler excecuteAuction:nonBidders:auctionHistory:sessionDepth:completionBlock:] + 144 (ISAuctionHandler.m:144)
9  Save Pirate                    0x10f57d0c9 -[ISProgRvManager makeAuction] + 219 (ISProgRvManager.m:219)
10 Save Pirate                    0x10f581101 -[ISProgRvManager onAuctionTriggered] + 727 (ISProgRvManager.m:727)
11 Save Pirate                    0x10f5ae01e -[ISRvAuctionTrigger onTick:] + 80 (ISRvAuctionTrigger.m:80)
12 Foundation                     0x7fff20871584 __NSFireTimer
13 CoreFoundation                 0x7fff203a9112 (Отсутствует)
14 CoreFoundation                 0x7fff203a8be5 (Отсутствует)
15 CoreFoundation                 0x7fff203a8198 (Отсутствует)
16 CoreFoundation                 0x7fff203a2826 (Отсутствует)
17 CoreFoundation                 0x7fff203a1b9e (Отсутствует)
18 GraphicsServices               0x7fff2b793db3 (Отсутствует)
19 UIKitCore                      0x7fff2466d40f (Отсутствует)
20 UIKitCore                      0x7fff24672320 (Отсутствует)
21 Save Pirate                    0x10e852270 main + 14 (main.m:14)
22 libdyld.dylib                  0x7fff20257409 (Отсутствует)
23 ???                            0x1 (Отсутствует)

**Comment by 0x7fs** [comment]
This doesn't appear to be an issue anymore using version 7.0.3
