### ISSUE TITLE
 I can't show admob ads (ANDROID)

### ISSUE THREAD

**Issue by omeryilmazel** [wowmaking/react-native-iron-source#74]
**I can't show ADMOB ads but unity facebook and ironsource show. Please help me**

### Rewarded Callback Log
> I/ironSourceSDK: API: RewardedVideoManager:isRewardedVideoAvailable()
> I/ironSourceSDK: INTERNAL: AdMob:isRewardedVideoAvailable()
> I/ironSourceSDK: API: isRewardedVideoAvailable():false

### Interstitial Callback Log
> I/ironSourceSDK: API: setInterstitialListener(ISListener)
> I/ironSourceSDK: API: loadInterstitial()
> I/ironSourceSDK: INTERNAL: automation_log:1613735066528 text: Auction Handler: auction trial 1 out of 1 max trials
> I/ironSourceSDK: INTERNAL: automation_log:1613735067843 text: IS: updateWaterfall() - next waterfall is 1AdMob,
> I/ironSourceSDK: CALLBACK: onInterstitialAdLoadFailed(errorCode:509, errorMessage:No ads to show)

### Banner Callback Log
> I/ironSourceSDK: API: createBanner()
> I/ironSourceSDK: API: setBannerListener()
> I/ironSourceSDK: ADAPTER_API: BannerSmash AdMob loadBanner
> I/ironSourceSDK: ADAPTER_API: BannerSmash AdMob state=LOAD_IN_PROGRESS
> I/ironSourceSDK: ADAPTER_API: BannerSmash AdMob onBannerAdLoadFailed()
> I/ironSourceSDK: ADAPTER_API: BannerSmash AdMob state=LOAD_FAILED
>  I/ironSourceSDK: CALLBACK: onBannerAdLoadFailed()  error=errorCode:606, errorMessage:No ads to show

**Comment by MaximeTKT** [comment]
@omeryilmazel Hey, I'm facing the same issue. How did you fix that?
